import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#fff7e3] custom-color">
        <header className="fixed w-full z-50">
          <Navbar/>
        </header>
          <main className="min-h-screen">
        {children}
          </main>
          <Footer />
      </body>
    </html>
  );
}
