import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#f3f3f3] custom-color n">
        <header className="fixed w-full z-50">
          <Navbar />
        </header>
        <main >
          {children}
        </main>
        <footer className="w-full z-50">
          <Footer />
        </footer>
      </body>
    </html>
  );
}